//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edulink.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edulink.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string About_Close {
            get {
                return ResourceManager.GetString("About.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrew.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer name.
        /// </summary>
        internal static string FirstSteps_Computer_Name {
            get {
                return ResourceManager.GetString("FirstSteps.Computer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name to identify this computer on the teacher&apos;s screen..
        /// </summary>
        internal static string FirstSteps_Computer_Name_Description {
            get {
                return ResourceManager.GetString("FirstSteps.Computer.Name.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the teacher&apos;s computer IP address and port to connect..
        /// </summary>
        internal static string FirstSteps_Connection_Description {
            get {
                return ResourceManager.GetString("FirstSteps.Connection.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        internal static string FirstSteps_Connection_IPAddress {
            get {
                return ResourceManager.GetString("FirstSteps.Connection.IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string FirstSteps_Connection_Port {
            get {
                return ResourceManager.GetString("FirstSteps.Connection.Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string FirstSteps_Password_ChangePassword {
            get {
                return ResourceManager.GetString("FirstSteps.Password.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a password to protect these settings from being changed by a student..
        /// </summary>
        internal static string FirstSteps_Password_Description {
            get {
                return ResourceManager.GetString("FirstSteps.Password.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        internal static string FirstSteps_Password_SetPassword {
            get {
                return ResourceManager.GetString("FirstSteps.Password.SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edulink setup.
        /// </summary>
        internal static string FirstSteps_Title {
            get {
                return ResourceManager.GetString("FirstSteps.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string FirstSteps_Welcome {
            get {
                return ResourceManager.GetString("FirstSteps.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        internal static string FirstSteps_Welcome_GetStarted {
            get {
                return ResourceManager.GetString("FirstSteps.Welcome.GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string InputDialog_Cancel {
            get {
                return ResourceManager.GetString("InputDialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string InputDialog_Ok {
            get {
                return ResourceManager.GetString("InputDialog.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is already running.
        /// </summary>
        internal static string Message_Content_AlreadyRunning {
            get {
                return ResourceManager.GetString("Message.Content.AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to use a weak password?.
        /// </summary>
        internal static string Message_Content_AreYouSureWeakPassword {
            get {
                return ResourceManager.GetString("Message.Content.AreYouSureWeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password.
        /// </summary>
        internal static string Message_Content_EnterAPassword {
            get {
                return ResourceManager.GetString("Message.Content.EnterAPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart the application as administrator.
        /// </summary>
        internal static string Message_Content_FailedToRestartAsAdmin {
            get {
                return ResourceManager.GetString("Message.Content.FailedToRestartAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        internal static string Message_Content_IncorrectPassword {
            get {
                return ResourceManager.GetString("Message.Content.IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is strongly recommended to set a password. Would you like to set a password now?.
        /// </summary>
        internal static string Message_Content_NoPasswordSet {
            get {
                return ResourceManager.GetString("Message.Content.NoPasswordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string Message_Content_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Message.Content.PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Message_Title_Error {
            get {
                return ResourceManager.GetString("Message.Title.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Message_Title_Information {
            get {
                return ResourceManager.GetString("Message.Title.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from teacher.
        /// </summary>
        internal static string Message_Title_MessageFromTeacher {
            get {
                return ResourceManager.GetString("Message.Title.MessageFromTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Message_Title_Success {
            get {
                return ResourceManager.GetString("Message.Title.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Message_Title_Warning {
            get {
                return ResourceManager.GetString("Message.Title.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MessageDialog_Cancel {
            get {
                return ResourceManager.GetString("MessageDialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MessageDialog_No {
            get {
                return ResourceManager.GetString("MessageDialog.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageDialog_Ok {
            get {
                return ResourceManager.GetString("MessageDialog.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string MessageDialog_Reply {
            get {
                return ResourceManager.GetString("MessageDialog.Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MessageDialog_Yes {
            get {
                return ResourceManager.GetString("MessageDialog.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PasswordDialog_Cancel {
            get {
                return ResourceManager.GetString("PasswordDialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string PasswordDialog_Confirm {
            get {
                return ResourceManager.GetString("PasswordDialog.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string PasswordDialog_ConfirmPassword {
            get {
                return ResourceManager.GetString("PasswordDialog.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string PasswordDialog_CurrentPassword {
            get {
                return ResourceManager.GetString("PasswordDialog.CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordDialog_Password {
            get {
                return ResourceManager.GetString("PasswordDialog.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength: {0}.
        /// </summary>
        internal static string PasswordDialog_Strength {
            get {
                return ResourceManager.GetString("PasswordDialog.Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string PasswordDialog_Strength_Medium {
            get {
                return ResourceManager.GetString("PasswordDialog.Strength.Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string PasswordDialog_Strength_Strong {
            get {
                return ResourceManager.GetString("PasswordDialog.Strength.Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very strong.
        /// </summary>
        internal static string PasswordDialog_Strength_VeryStrong {
            get {
                return ResourceManager.GetString("PasswordDialog.Strength.VeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        internal static string PasswordDialog_Strength_Weak {
            get {
                return ResourceManager.GetString("PasswordDialog.Strength.Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string PasswordDialog_Title_ChangePassword {
            get {
                return ResourceManager.GetString("PasswordDialog.Title.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string PasswordDialog_Title_EnterPassword {
            get {
                return ResourceManager.GetString("PasswordDialog.Title.EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        internal static string PasswordDialog_Title_SetPassword {
            get {
                return ResourceManager.GetString("PasswordDialog.Title.SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Settings_Connection {
            get {
                return ResourceManager.GetString("Settings.Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        internal static string Settings_Connection_IPAddress {
            get {
                return ResourceManager.GetString("Settings.Connection.IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer name.
        /// </summary>
        internal static string Settings_Connection_Name {
            get {
                return ResourceManager.GetString("Settings.Connection.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Settings_Connection_Port {
            get {
                return ResourceManager.GetString("Settings.Connection.Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string Settings_Miscellaneous {
            get {
                return ResourceManager.GetString("Settings.Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application.
        /// </summary>
        internal static string Settings_Miscellaneous_ExitApplication {
            get {
                return ResourceManager.GetString("Settings.Miscellaneous.ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings.
        /// </summary>
        internal static string Settings_Miscellaneous_ResetSettings {
            get {
                return ResourceManager.GetString("Settings.Miscellaneous.ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart application.
        /// </summary>
        internal static string Settings_Miscellaneous_RestartApplication {
            get {
                return ResourceManager.GetString("Settings.Miscellaneous.RestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Settings_Miscellaneous_Save {
            get {
                return ResourceManager.GetString("Settings.Miscellaneous.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Settings_Password {
            get {
                return ResourceManager.GetString("Settings.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Settings_Password_ChangePassword {
            get {
                return ResourceManager.GetString("Settings.Password.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        internal static string Settings_Password_SetPassword {
            get {
                return ResourceManager.GetString("Settings.Password.SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and restart.
        /// </summary>
        internal static string Settings_SaveAndRestart {
            get {
                return ResourceManager.GetString("Settings.SaveAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string Settings_Theme_Auto {
            get {
                return ResourceManager.GetString("Settings.Theme.Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings.Theme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings.Theme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string TrayContextMenu_About {
            get {
                return ResourceManager.GetString("TrayContextMenu.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string TrayContextMenu_Connection_Status_Connected {
            get {
                return ResourceManager.GetString("TrayContextMenu.Connection.Status.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string TrayContextMenu_Connection_Status_Disconnected {
            get {
                return ResourceManager.GetString("TrayContextMenu.Connection.Status.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TrayContextMenu_Exit {
            get {
                return ResourceManager.GetString("TrayContextMenu.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TrayContextMenu_Settings {
            get {
                return ResourceManager.GetString("TrayContextMenu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater.
        /// </summary>
        internal static string TrayContextMenu_Updater {
            get {
                return ResourceManager.GetString("TrayContextMenu.Updater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string TrayContextMenu_Updater_Available {
            get {
                return ResourceManager.GetString("TrayContextMenu.Updater.Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        internal static string TrayContextMenu_Updater_UpToDate {
            get {
                return ResourceManager.GetString("TrayContextMenu.Updater.UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        internal static string UpdaterDialog_CheckForUpdates {
            get {
                return ResourceManager.GetString("UpdaterDialog.CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string UpdaterDialog_ChekingUpdates {
            get {
                return ResourceManager.GetString("UpdaterDialog.ChekingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently using version {0}.
        /// </summary>
        internal static string UpdaterDialog_CurrentVersion {
            get {
                return ResourceManager.GetString("UpdaterDialog.CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not close this window.
        /// </summary>
        internal static string UpdaterDialog_DoNotCloseWindow {
            get {
                return ResourceManager.GetString("UpdaterDialog.DoNotCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater.
        /// </summary>
        internal static string UpdaterDialog_Title {
            get {
                return ResourceManager.GetString("UpdaterDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdaterDialog_Update {
            get {
                return ResourceManager.GetString("UpdaterDialog.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} of {1} is now available.
        /// </summary>
        internal static string UpdaterDialog_UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdaterDialog.UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update in progress.
        /// </summary>
        internal static string UpdaterDialog_UpdateInProgress {
            get {
                return ResourceManager.GetString("UpdaterDialog.UpdateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        internal static string UpdaterDialog_UpToDate {
            get {
                return ResourceManager.GetString("UpdaterDialog.UpToDate", resourceCulture);
            }
        }
    }
}
