//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edulink.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edulink.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string About_Close {
            get {
                return ResourceManager.GetString("About.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrew.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh.
        /// </summary>
        internal static string DesktopDialog_Message_FailedToRefresh {
            get {
                return ResourceManager.GetString("DesktopDialog.Message.FailedToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving image.
        /// </summary>
        internal static string DesktopDialog_ReceivingImage {
            get {
                return ResourceManager.GetString("DesktopDialog.ReceivingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string DesktopDialog_Refresh {
            get {
                return ResourceManager.GetString("DesktopDialog.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string DesktopDialog_Save {
            get {
                return ResourceManager.GetString("DesktopDialog.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new name.
        /// </summary>
        internal static string Input_Content_RenameComputer {
            get {
                return ResourceManager.GetString("Input.Content.RenameComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your link.
        /// </summary>
        internal static string Input_Content_SendLink {
            get {
                return ResourceManager.GetString("Input.Content.SendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your message.
        /// </summary>
        internal static string Input_Content_SendMessage {
            get {
                return ResourceManager.GetString("Input.Content.SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename computer.
        /// </summary>
        internal static string Input_Title_RenameComputer {
            get {
                return ResourceManager.GetString("Input.Title.RenameComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send link.
        /// </summary>
        internal static string Input_Title_SendLink {
            get {
                return ResourceManager.GetString("Input.Title.SendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        internal static string Input_Title_SendMessage {
            get {
                return ResourceManager.GetString("Input.Title.SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string InputDialog_Cancel {
            get {
                return ResourceManager.GetString("InputDialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string InputDialog_Ok {
            get {
                return ResourceManager.GetString("InputDialog.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all computers.
        /// </summary>
        internal static string Main_AllComputers {
            get {
                return ResourceManager.GetString("Main.AllComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string Main_AreYouSureYouWantToExit {
            get {
                return ResourceManager.GetString("Main.AreYouSureYouWantToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block input.
        /// </summary>
        internal static string Main_Commands_BlockInput {
            get {
                return ResourceManager.GetString("Main.Commands.BlockInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude from preview.
        /// </summary>
        internal static string Main_Commands_ExcludeFromPreview {
            get {
                return ResourceManager.GetString("Main.Commands.ExcludeFromPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include on preview.
        /// </summary>
        internal static string Main_Commands_IncludeOnPreview {
            get {
                return ResourceManager.GetString("Main.Commands.IncludeOnPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen.
        /// </summary>
        internal static string Main_Commands_LockScreen {
            get {
                return ResourceManager.GetString("Main.Commands.LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string Main_Commands_LogOff {
            get {
                return ResourceManager.GetString("Main.Commands.LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Main_Commands_Rename {
            get {
                return ResourceManager.GetString("Main.Commands.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string Main_Commands_ResetPassword {
            get {
                return ResourceManager.GetString("Main.Commands.ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Main_Commands_Restart {
            get {
                return ResourceManager.GetString("Main.Commands.Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart application.
        /// </summary>
        internal static string Main_Commands_RestartApplication {
            get {
                return ResourceManager.GetString("Main.Commands.RestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send link.
        /// </summary>
        internal static string Main_Commands_SendLink {
            get {
                return ResourceManager.GetString("Main.Commands.SendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        internal static string Main_Commands_SendMessage {
            get {
                return ResourceManager.GetString("Main.Commands.SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Main_Commands_Shutdown {
            get {
                return ResourceManager.GetString("Main.Commands.Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle mute.
        /// </summary>
        internal static string Main_Commands_ToggleMute {
            get {
                return ResourceManager.GetString("Main.Commands.ToggleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock input.
        /// </summary>
        internal static string Main_Commands_UnblockInput {
            get {
                return ResourceManager.GetString("Main.Commands.UnblockInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update application.
        /// </summary>
        internal static string Main_Commands_UpdateApplication {
            get {
                return ResourceManager.GetString("Main.Commands.UpdateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View desktop.
        /// </summary>
        internal static string Main_Commands_ViewDesktop {
            get {
                return ResourceManager.GetString("Main.Commands.ViewDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected computers ({0}).
        /// </summary>
        internal static string Main_ConnectedComputers {
            get {
                return ResourceManager.GetString("Main.ConnectedComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected at {0:HH:mm:ss}.
        /// </summary>
        internal static string Main_List_ToolTip_ConnectionTime {
            get {
                return ResourceManager.GetString("Main.List.ToolTip.ConnectionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint: {0}.
        /// </summary>
        internal static string Main_List_ToolTip_Endpoint {
            get {
                return ResourceManager.GetString("Main.List.ToolTip.Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        internal static string Main_List_ToolTip_Name {
            get {
                return ResourceManager.GetString("Main.List.ToolTip.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string Main_List_ToolTip_Version {
            get {
                return ResourceManager.GetString("Main.List.ToolTip.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Main_Menu_File {
            get {
                return ResourceManager.GetString("Main.Menu.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Main_Menu_File_Exit {
            get {
                return ResourceManager.GetString("Main.Menu.File.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Main_Menu_File_Settings {
            get {
                return ResourceManager.GetString("Main.Menu.File.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Main_Menu_Help {
            get {
                return ResourceManager.GetString("Main.Menu.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Main_Menu_Help_About {
            get {
                return ResourceManager.GetString("Main.Menu.Help.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater.
        /// </summary>
        internal static string Main_Menu_Help_Updater {
            get {
                return ResourceManager.GetString("Main.Menu.Help.Updater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Main_Menu_Options {
            get {
                return ResourceManager.GetString("Main.Menu.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        internal static string Main_Menu_Options_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Main.Menu.Options.AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Main_Menu_View {
            get {
                return ResourceManager.GetString("Main.Menu.View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        internal static string Main_Menu_View_FullScreen {
            get {
                return ResourceManager.GetString("Main.Menu.View.FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Main_Menu_View_Refresh {
            get {
                return ResourceManager.GetString("Main.Menu.View.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshed.
        /// </summary>
        internal static string Main_Refreshed {
            get {
                return ResourceManager.GetString("Main.Refreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string Main_SortBy {
            get {
                return ResourceManager.GetString("Main.SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection time.
        /// </summary>
        internal static string Main_SortBy_ConnectionTime {
            get {
                return ResourceManager.GetString("Main.SortBy.ConnectionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Main_SortBy_Name {
            get {
                return ResourceManager.GetString("Main.SortBy.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Main_SortBy_Version {
            get {
                return ResourceManager.GetString("Main.SortBy.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for computers.
        /// </summary>
        internal static string Main_WaitingForComputers {
            get {
                return ResourceManager.GetString("Main.WaitingForComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is already running.
        /// </summary>
        internal static string Message_Content_AlreadyRunning {
            get {
                return ResourceManager.GetString("Message.Content.AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave without saving changes?.
        /// </summary>
        internal static string Message_Content_AreYouSureYouWantToLeaveWithoutSavingChanges {
            get {
                return ResourceManager.GetString("Message.Content.AreYouSureYouWantToLeaveWithoutSavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t initialize server. Please change the settings..
        /// </summary>
        internal static string Message_Content_CouldntInitializeServer {
            get {
                return ResourceManager.GetString("Message.Content.CouldntInitializeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No clients selected.
        /// </summary>
        internal static string Message_Content_NoClientsSelected {
            get {
                return ResourceManager.GetString("Message.Content.NoClientsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Message_Title_Error {
            get {
                return ResourceManager.GetString("Message.Title.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Message_Title_Information {
            get {
                return ResourceManager.GetString("Message.Title.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from {0}.
        /// </summary>
        internal static string Message_Title_MessageFrom {
            get {
                return ResourceManager.GetString("Message.Title.MessageFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from teacher.
        /// </summary>
        internal static string Message_Title_MessageFromTeacher {
            get {
                return ResourceManager.GetString("Message.Title.MessageFromTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Message_Title_Success {
            get {
                return ResourceManager.GetString("Message.Title.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Message_Title_Warning {
            get {
                return ResourceManager.GetString("Message.Title.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MessageDialog_Cancel {
            get {
                return ResourceManager.GetString("MessageDialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MessageDialog_No {
            get {
                return ResourceManager.GetString("MessageDialog.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageDialog_Ok {
            get {
                return ResourceManager.GetString("MessageDialog.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string MessageDialog_Reply {
            get {
                return ResourceManager.GetString("MessageDialog.Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string MessageDialog_Retry {
            get {
                return ResourceManager.GetString("MessageDialog.Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MessageDialog_Yes {
            get {
                return ResourceManager.GetString("MessageDialog.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Settings_Connection {
            get {
                return ResourceManager.GetString("Settings.Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Settings_Connection_Port {
            get {
                return ResourceManager.GetString("Settings.Connection.Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address: {0}.
        /// </summary>
        internal static string Settings_IPAddress {
            get {
                return ResourceManager.GetString("Settings.IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        internal static string Settings_Message_CopiedToClipboard {
            get {
                return ResourceManager.GetString("Settings.Message.CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Settings_Message_Saved {
            get {
                return ResourceManager.GetString("Settings.Message.Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string Settings_Miscellaneous {
            get {
                return ResourceManager.GetString("Settings.Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application.
        /// </summary>
        internal static string Settings_Miscellaneous_ExitApplication {
            get {
                return ResourceManager.GetString("Settings.Miscellaneous.ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings.
        /// </summary>
        internal static string Settings_Miscellaneous_ResetSettings {
            get {
                return ResourceManager.GetString("Settings.Miscellaneous.ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart application.
        /// </summary>
        internal static string Settings_Miscellaneous_RestartApplication {
            get {
                return ResourceManager.GetString("Settings.Miscellaneous.RestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Settings_Miscellaneous_Save {
            get {
                return ResourceManager.GetString("Settings.Miscellaneous.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Settings_Notifications {
            get {
                return ResourceManager.GetString("Settings.Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer disconnected.
        /// </summary>
        internal static string Settings_Notifications_ComputerDisconnected {
            get {
                return ResourceManager.GetString("Settings.Notifications.ComputerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Settings_Preview {
            get {
                return ResourceManager.GetString("Settings.Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Settings_Preview_Enabled {
            get {
                return ResourceManager.GetString("Settings.Preview.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update frequency: {0}ms..
        /// </summary>
        internal static string Settings_Preview_Frequency {
            get {
                return ResourceManager.GetString("Settings.Preview.Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and restart.
        /// </summary>
        internal static string Settings_SaveAndRestart {
            get {
                return ResourceManager.GetString("Settings.SaveAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string Settings_Theme_Auto {
            get {
                return ResourceManager.GetString("Settings.Theme.Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings.Theme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings.Theme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has disconnected.
        /// </summary>
        internal static string TaskbarIcon_Content_ComputerDisconnected {
            get {
                return ResourceManager.GetString("TaskbarIcon.Content.ComputerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is now available.
        /// </summary>
        internal static string TaskbarIcon_Content_UpdateAvailable {
            get {
                return ResourceManager.GetString("TaskbarIcon.Content.UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer disconnected.
        /// </summary>
        internal static string TaskbarIcon_Title_ComputerDisconnected {
            get {
                return ResourceManager.GetString("TaskbarIcon.Title.ComputerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string TaskbarIcon_Title_UpdateAvailable {
            get {
                return ResourceManager.GetString("TaskbarIcon.Title.UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        internal static string UpdaterDialog_CheckForUpdates {
            get {
                return ResourceManager.GetString("UpdaterDialog.CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string UpdaterDialog_CheckingUpdates {
            get {
                return ResourceManager.GetString("UpdaterDialog.CheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently using version {0}.
        /// </summary>
        internal static string UpdaterDialog_CurrentVersion {
            get {
                return ResourceManager.GetString("UpdaterDialog.CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not close this window.
        /// </summary>
        internal static string UpdaterDialog_DoNotCloseWindow {
            get {
                return ResourceManager.GetString("UpdaterDialog.DoNotCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser.
        /// </summary>
        internal static string UpdaterDialog_OpenInBrowser {
            get {
                return ResourceManager.GetString("UpdaterDialog.OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater.
        /// </summary>
        internal static string UpdaterDialog_Title {
            get {
                return ResourceManager.GetString("UpdaterDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdaterDialog_Update {
            get {
                return ResourceManager.GetString("UpdaterDialog.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} of {1} is now available.
        /// </summary>
        internal static string UpdaterDialog_UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdaterDialog.UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update in progress.
        /// </summary>
        internal static string UpdaterDialog_UpdateInProgress {
            get {
                return ResourceManager.GetString("UpdaterDialog.UpdateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        internal static string UpdaterDialog_UpToDate {
            get {
                return ResourceManager.GetString("UpdaterDialog.UpToDate", resourceCulture);
            }
        }
    }
}
